language: node_js
env:
  global:
    - NODE_ENV=test
    - SECRET_KEY=thisispropertyprolite
    - DB_USERNAME=okaforchidimma
    - DB_PASSWORD=Jennylove19
    - DBNAME=propertyprolite_testdb
services:
  - postgresql
before_script:
  - psql -c 'create database propertyprolite_testdb;' -U postgres
  - psql -c "CREATE USER okaforchidimma WITH PASSWORD 'Jennylove19';" -U postgres
  - npm run migrate
  - npm run migrate:test
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
install:
  - npm install

script: npm test
after_success: 'npm run coverage'
after_failure: 'cat /home/travis/.npm/_logs/2019-04-*-debug.log'


