const properties = [
  {
    id: 1,
    owner: 3,
    status: 'Available',
    price: 6844.22,
    country: 'Nigeria',
    state: 'Anambra',
    city: 'Awka',
    address: 'No 4 Abaji Street',
    no_of_rooms: 2,
    fraud: false,
    type: 'duplex',
    adv_desc: 'it is a little bungalow',
    adv_purpose: 'rent',
    duration: '2 years',
    created_on: new Date(),
    image_url: 'http://res.cloudinary.com/okafor-chidimma/image/upload/v1562108668/ybxnh9g2jlkiho1ubpq2.jpg',
  },
  {
    id: 2,
    owner: 3,
    status: 'Available',
    price: 16844.55,
    country: 'Nigeria',
    state: 'Fct',
    city: 'Abuja',
    address: 'No 4 gana Street',
    no_of_rooms: 2,
    type: 'bungalow',
    fraud: true,
    adv_desc: 'it is a little bungalow',
    adv_purpose: 'rent',
    duration: '11 months',
    created_on: new Date(),
    image_url: 'http://res.cloudinary.com/okafor-chidimma/image/upload/v1562108620/upmagwkejxcgfcjgwzgq.jpg"',

  },
  {
    id: 3,
    owner: 1,
    fraud: false,
    status: 'Available',
    price: 16384.99,
    country: 'Nigeria',
    state: 'Fct',
    city: 'Abuja',
    address: 'No 4 Uzoma Street',
    no_of_rooms: 4,
    type: 'bungalow',
    adv_purpose: 'rent',
    duration: '11 months',
    adv_desc: 'it is a little bungalow',
    created_on: new Date(),
    image_url: 'http://res.cloudinary.com/okafor-chidimma/image/upload/v1562108557/kssgwny1akzpeect09lf.jpg',

  },

];
export default properties;
